// Generates src/app/assets/mascot.ts: the six mascot faces as static SVG, one per game mood.
// Art: "Toon Head" by Johan Melin (https://www.johanmelin.com), CC BY 4.0, rendered with DiceBear.
// Changes: one fixed character, a face per mood, cropped to the head. Run: node scripts/build-mascot.mjs
import { createAvatar } from '@dicebear/core'
import * as toonHead from '@dicebear/toon-head'
import { writeFileSync } from 'node:fs'

const CHARACTER = {
  seed: 'typelight',
  hair: ['sideComed'],
  hairColor: ['2c1b18'],
  skinColor: ['c68e7a'],
  clothes: ['tShirt'],
  clothesColor: ['3fae5a'],
  beardProbability: 0,
  rearHairProbability: 0,
}

// [eyes, mouth, eyebrows]
const FACES = {
  idle: ['happy', 'smile', 'neutral'],
  happy: ['happy', 'laugh', 'happy'],
  thrilled: ['bow', 'laugh', 'raised'],
  sad: ['humble', 'sad', 'sad'],
  worried: ['wide', 'sad', 'sad'],
  panic: ['wide', 'agape', 'raised'],
}

// The avatar is a bust on a 768 box; this window keeps the head and a bit of shoulder.
const CROP = '69 6 630 630'

const svgFor = (mood, [eyes, mouth, eyebrows]) =>
  createAvatar(toonHead, { ...CHARACTER, eyes: [eyes], mouth: [mouth], eyebrows: [eyebrows] })
    .toString()
    .replace(/<metadata[\s\S]*?<\/metadata>/, '')
    .replace('viewBox="0 0 768 768"', `viewBox="${CROP}"`)
    .replace(/id="([^"]+)"/g, `id="mascot-${mood}-$1"`)
    .replace(/url\(#([^)]+)\)/g, `url(#mascot-${mood}-$1)`)

const entries = Object.entries(FACES).map(([mood, face]) => `  ${mood}: ${JSON.stringify(svgFor(mood, face))},`)

writeFileSync(
  'src/app/assets/mascot.ts',
  `// Generated by scripts/build-mascot.mjs. Do not edit by hand.
// "Toon Head" by Johan Melin (https://www.johanmelin.com), CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
// Adapted: one fixed character, a face per mood, cropped to the head.
export const MASCOT_FACES = {
${entries.join('\n')}
} as const
`,
)
console.log('wrote src/app/assets/mascot.ts')
